### ISSUE TITLE
ALice doesn't like questions ending in multiple punctuation or single chracter questions

### ISSUE THREAD

**Issue by GRyall** [etattershall/toddler-chatbot#1]
Alice appears to be a stickler for proper ppunctuation and throws an IndexError at you if you end your question with multiple punctuation marks (e.g. "What are you talking about!?!), unless the final one is a question mark. 

She also doesn't like single character interactions and throws index errors at me

**Comment by etattershall** [comment]
Fixed single character interactions, but not able to replicate the multiple punctuation mark error

**Comment by GRyall** [comment]
I can't reproduce the first part of this issue with the latest version and the last part has been fixed. (Yes I should have put in two issues).
